### PR TITLE
Use device_set_uncaptured_error_callback for error handling

### PR DESCRIPTION
**Pull request by JopStro**
Hi, I have been recently working on my own set of bindings for webgpu, but stumbled upon these bindings recently and really like the way the external API is handled. However, after looking at the internals, I have a few issues with it. This is one of the first ones. 

This just changes the error handling to use `device_set_uncaptured_error_callback` instead of the push and pop error scope procedures, reducing boiler plate and removing the need to reference the device in most cases. I may extend this a little further by replacing the printing in the error callback with a user callback system which hijacks the existing wrapped `device_set_uncaptured_error_callback` procedure and possibly removing the error scope procedures from the wrapper as the error return values should achieve the same aim in most use cases.

But I thought I'd better inform you of my existence and get some feedback before I continue.

P.S Sorry if I come off a little harsh (it's clear from the code that you're quite new to odin), I just figured since we're both working on the same thing at the same time and your version is a little further along it would be easier for me to help out here.

### CODE REVIEW

**Comment by JopStro** [comment]
Also sorry about the pointless merge, i did it on accident and I'm not sure how to fanangle git to revert it.

**Comment by Capati** [comment]
Hi, thanks for your contribution. I didn't share this repo in the Odin community because I want to test more, now you can help me. Yes, I’m new to both Odin and WGPU, but I tried to make things simple with the wrapper version, and I get some references from the python and go bindings.

About the changes:

-  `map_async` is synchronous because the data is returned immediately from `map_read`. We could hide the procs `get_mapped_range`, `map_async` and `unmap` from the user?

- Removing the error scope, how we can get errors for every operation in the same context? For example, a error when get a suboptimal surface texture we can skip a frame, like in [this example](https://github.com/gfx-rs/wgpu-native/blob/trunk/examples/triangle/main.c#L324).

- When you say "removing the need to reference the device in most cases" is this related to push and pop scope? It's not mandatory for reference counting?

**Comment by JopStro** [comment]
With map_async, I think since it is intended to be used asyncronously we shouldn't enforce syncronosity, what if the person using the library needs that behaviour?

If we're handling every error, using the error scope is unnessasary. we can just use the uncaptured error callback like in this PR. also by using the error scope in the wrapper we restrict the user from being able to use it themselves like in the example you gave.

Because of the usage of error scopes for error handling, the device pointer had to be passed down to everything that had methods that could throw errors. By using the uncaptured error callback we can just pass down a pointer to the callback's user data as that gives us all we'll need for the idiomatic error handling.

**Comment by JopStro** [comment]
Looking closer at the example you linked, with the recent changes I just made to the branch, the behavior could be achieved by checking the returned error and getting the error message using `device_get_error_message` removing the need to use an error scope at all.
The only issue could be if a uncaught error callback was set it would still be called, which wouldn't happen with an error scope, I was thinking of adding some special handling to address this but I think it might just be easier to allow the user to use error scopes when needed and make sure the wrapper still works when the uncaught error callback is disabled.

**Comment by JopStro** [comment]
Just took a look at `map_read`, why not just put the code to make it synchronous in that procedure instead? then you get both the ability to have a synchronous read procedure with `map_read`, with the async one also working for those who need it.

**Comment by Capati** [comment]
About the reference, you removed `wgpu.device_reference`, for some objects creation is not necessary?

Yes, we can make `map_read` and `map_write` synchronous and not enforce in the async.

**Comment by JopStro** [comment]
For most objects the device was only being referenced so it could be used with `push_error_scope` and `pop_error_scope`, since this change replaces that, the device no longer needs to be referenced in most cases. Also I think one of the objects referenced the device without using it at all, so I removed that too.

**Comment by JopStro** [comment]
Also I'm happy with this patch for now, the possible issues error scopes stuff can be easily addressed serparately. Just note that, It doesn't break anything per say but it does require the user to now handle the display of device error messages themselves, either automatically via the modified `device_set_uncaptured_error_callback` procedure or on a case by case basis using `device_get_error_message`.

**Pull request merged**
